### ISSUE TITLE
Improve Place Image

### ISSUE THREAD

**Issue by quasado** [GravitAG/gravit#113]
<a href="https://github.com/quasado"><img src="https://avatars.githubusercontent.com/u/2025836?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [quasado](https://github.com/quasado)**
_Saturday Aug 09, 2014 at 09:05 GMT_
_Originally opened as https://github.com/quasado/app.gravit.io/issues/59_

----

Should improve place image - if document is not saved still allow inserting but embedded it. If document is saved and image is not relative, ask to copy image relative to document.

**Comment by alexmigf** [comment]
Place image don't work in Windows 8.1, it works on Chrome.
