### ISSUE TITLE
Not able to paste text as object

### ISSUE THREAD

**Issue by quasado** [GravitAG/gravit#117]
<a href="https://github.com/chunwui"><img src="https://avatars.githubusercontent.com/u/4509354?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chunwui](https://github.com/chunwui)**
_Saturday Aug 09, 2014 at 09:26 GMT_
_Originally opened as https://github.com/quasado/app.gravit.io/issues/63_

----

When paste the text from the clipboard, nothing happens.  It should paste as a text object.

If it is paste inside an existing text object, it become quirky.

**Comment by anderswelt** [comment]
Closed for now needs re-thinking because of browser only version
