### ISSUE TITLE
Open saved files do not work (Ubuntu, Chrome Extension)

### ISSUE THREAD

**Issue by quasado** [GravitAG/gravit#152]
<a href="https://github.com/pierrebayartz"><img src="https://avatars.githubusercontent.com/u/1038194?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pierrebayartz](https://github.com/pierrebayartz)**
_Thursday Aug 28, 2014 at 09:37 GMT_
_Originally opened as https://github.com/quasado/app.gravit.io/issues/98_

----

I'm using the chrome extension on ubuntu and it is not possible to open a saved file from gravit. Perhaps the problem is the missing content for the filetype dropdown field 

Regards

**Comment by anderswelt** [comment]
1.0 no longer supports files so this is no longer valid. This btw is a bug in Chrome and already added by us in their bugtracker :)

**Comment by brycethorup** [comment]
@anderswelt Could you post a link to the Chrome bugtracker issue.? I am curious about what is being considered a bug. I've implemented these sorts of file operations in my projects several times and have never had this sort of issue.
