### ISSUE TITLE
Fuzzy edges

### ISSUE THREAD

**Issue by pseudonymcp** [GravitAG/gravit#184]
Applying a solid border on a rectangle looks fuzzy. In this example I have a 5 px border (outside). This makes it hard to work on pixel-perfect designs.
Windows 7 64-bit (app installed locally)
![snag-0001](https://cloud.githubusercontent.com/assets/1522647/4666304/3dfa8f0a-5552-11e4-9e25-cdd8f99216eb.png)

**Comment by anderswelt** [comment]
you need to either half-pixel align for uneven stroke or make stroke inside
