### ISSUE TITLE
Error when saving --> artwork lost

### ISSUE THREAD

**Issue by pseudonymcp** [GravitAG/gravit#185]
![snag-0002](https://cloud.githubusercontent.com/assets/1522647/4666402/1d7ce33a-5553-11e4-9a2d-d1f441030219.png)
I got an uncaught node.js error when trying to save a file. Unfortunately there is no possibility to get the file back again (normally just saving would fail but I could still see my artwork). This makes it very risky to use the tool! Instead of this I see this error message inside the window and Gravit crashes (can't even be closed).

I think that errors should be handled in a way that the user can try to rescue the file or try to save it to another location.

Obviously Gravit mixed up the paths! I saved to D:\Screenshots ...
![snag-0003](https://cloud.githubusercontent.com/assets/1522647/4666449/90997982-5553-11e4-9f99-d969ed8cbaf4.png)
... but Gravit wants to save it to C:\Screenshots, which does not exist!!

Windows 7 64-bit (app installed locally)

**Comment by anderswelt** [comment]
1.0 has a new architecture and no longer saves files
