### ISSUE TITLE
Imported image - Crashed

### ISSUE THREAD

**Issue by Syenta** [GravitAG/gravit#192]
1. Gravit version used - latest beta version

2. A 1024x1144 119Kb black and white jpeg image from the internet which was dragged and dropped into Gravit. - ![smallhouse](https://cloud.githubusercontent.com/assets/9280419/4676688/1861605c-55de-11e4-980e-28fda1021271.jpg) and resized to fit

2. A second layer was added and titled "Roof".

3. The line tool was selected and colour changed to red.

4. Lines selection started.

5. Saved layer once roof completed

6. Gravit froze - unable to do anything include close down using File, Close or Red X top right. Program terminated via Cntrl + Alt + Del -> Task Manager -> Applications -> Gravit -> End Task.

**Comment by anderswelt** [comment]
should be fixed in 1.0 if not please re-report or re-open this - thx
