### ISSUE TITLE
Suggestion - Spacing and Removing shapes

### ISSUE THREAD

**Issue by Syenta** [GravitAG/gravit#194]
I find your spacing tool to be quite good however it is a little cumbersum IMHO. You need to select the side of the object you wish to align which is a great idea. Could you not have the object align with any edge as it nears another object? This would be a lot quicker than at present I feel.

Also I wanted to see if Gravit could use one object to remove its shape from another and I find this is not a feature in the latest version of Gravit.

Lastly, I have tried to constrain shapes eg stop a circle going elliptical. Most software I know uses the Ctrl key for this but Gravit seems to deselect an option when Ctrl is pressed. Is this normal?

Hope this helps

**Comment by anderswelt** [comment]
Fixed in 1.0 we've added both modes. 
For constraintment please use shift key
