### ISSUE TITLE
Mouse-Wheel-Zoom

### ISSUE THREAD

**Issue by jdittrich** [GravitAG/gravit#201]
User Story: *As a Designer I want a quick way to zoom in and out (without having to toggle tools to do so) in order control details and keep an eye on the overall look of the document.*

Related: #147 

Possible Implementations: 

* Wheel always zooms document ( [example](http://timmywil.github.io/jquery.panzoom/demo/index.html#focal) ) 
* Ctrl + Wheel zooms document

**Comment by anderswelt** [comment]
@anna-ignatenkova please implement with mouse-wheel (we might need to add a new dom event listener etc. on our widget not sure if I've already added such). Implement it like in the given example link with the focal point.
