### ISSUE TITLE
"Export All" Function Crashes

### ISSUE THREAD

**Issue by moneppo** [GravitAG/gravit#203]
Steps:
1. Create any document. Tried simple text and a few shapes.
2. Select "Export All" option in "Export" tab
3. Select folder for export.

Expected:
Some kind of export of the layers of my document.

Got:
![screen shot 2014-10-22 at 5 40 33 pm](https://cloud.githubusercontent.com/assets/5454101/4744861/1467c252-5a34-11e4-9ecd-984271250818.png)

Environment: Mac OSX Yosemite

**Comment by nosywiz** [comment]
I too got the same errors..
