### ISSUE TITLE
Replace www with non-www links on website

### ISSUE THREAD

**Issue by clarkwinkelmann** [GravitAG/gravit#212]
I'm certainly not at the right place for this comment but as you didn't open the Issues on your website repository I couldn't post there.

Not a very serious problem but on both websites (http://quasado.com/ and http://gravit.io/) you point to each other domain using the www subdomain but you clearly chose to use the non-www domain, as we are automatically redirected.

Removing the www from the link tags would be a bit nicer and will remove the need for a second DNS lookup for your visitors.

**Comment by anderswelt** [comment]
Closed as this will change in 1.0
