### ISSUE TITLE
Feature request: TTF

### ISSUE THREAD

**Issue by Zagatou** [GravitAG/gravit#225]
Please add these TTF's:
superphonic 
http://www.ufonts.com/fonts/superphonic-extended.html
superdigital
http://www.dafont.com/de/superdigital.font
designerblock
http://www.dafont.com/de/designer-block.font
visitor
http://www.dafont.com/de/visitor.font

**Comment by anderswelt** [comment]
closed as in 1.0 you can add all fonts yourself :)
