### ISSUE TITLE
Extend Text Editing Settings

### ISSUE THREAD

**Issue by anderswelt** [GravitAG/gravit#243]
Allow formatting selected text and not only whole paragraphs like now. This will actually require changing the way the text is painted because right now, we're creating a whole path from the paragraph but we would instead need to paint in parts when there's a different formatting.
Also allow setting a text color (only color) on paragraphs or selection and also allow removing color (use the color picker for that) which would cause to use the text's fill/stroke instead.

**Comment by anna-ignatenkova** [comment]
1. Should there be ability to set for the selection also:
- text opacity
- fill types other then color: gradient; pattern transform
- stroke size/pattern
? 
2. When we convert text to path we use one compound path for the whole text. How this should be converted (be split to compound paths) when we have different colors inside text (as compound path has one style): each char - one compound path, or group of chars of the same color (or gradient pattern) - one compound path?

**Comment by anderswelt** [comment]
@anna-ignatenkova:

1. No, only standard Text Properties (See the Stylable Properties) should be available as they're also reflectable in html which is important for our actual text editor

2. Not taking each char but each separately formatted span of text becomes it's own path when having a separate color (otherwise it can be added to the main path as it is now even with different font size and/or font-weight)

**Comment by anna-ignatenkova** [comment]
https://github.com/anderswelt: May you please check that the result is what was expected?

**Comment by anderswelt** [comment]
Put the color property into text properites and reset fill/border properties as talked then you can close this task.
