### ISSUE TITLE
Font styles seem to apply to first sentence completely

### ISSUE THREAD

**Issue by cekuhnen** [GravitAG/gravit#249]
![screen shot 2015-02-13 at 9 59 05 pm](https://cloud.githubusercontent.com/assets/11001547/6198387/d66eb18a-b3cb-11e4-81f6-8fc4f5b772f4.png)

Color can be used for everything, but font settings do not apply!

**Comment by anderswelt** [comment]
This is fixed in the upcoming release where you can apply color to selected text as well
