### ISSUE TITLE
Guide Layers cannot be snapped to?

### ISSUE THREAD

**Issue by cekuhnen** [GravitAG/gravit#253]
I cannot snap to anything I out into the background guide layer?

![screen shot 2015-02-14 at 9 04 38 am](https://cloud.githubusercontent.com/assets/11001547/6199816/a0ebf51a-b428-11e4-86ff-ac5ccf641e4a.png)

**Comment by anderswelt** [comment]
Yes, guide layers will be removed in the final release in favor of a smarter snapping algorithm

**Comment by cekuhnen** [comment]
Thanks for the info. Looking forward to it.
Better snapping will be much needed.

For layouting purpose I really like snap layers.
1. all it can to is to provide snap targets (lines arcs paths ...)
2. it is non printable.
no annoying show hide layer etc ...

**Comment by anderswelt** [comment]
Closing this off for now as of new smart guides feature
