### ISSUE TITLE
Place Image menu item does nothing

### ISSUE THREAD

**Issue by twolfson** [GravitAG/gravit#259]
Setup: Using desktop Linux `gravit` on Linux Mint 17.1. Open new artboard.

Actual behavior: Press "File -> Place Image...". Nothing happens. I can drag/drop images into interface fine.

Expected behavior: Pressing "File -> Place Image..." should open a file dialog and place the image into the artboard.

**Comment by anderswelt** [comment]
fixed in 1.0
