### ISSUE TITLE
Where the big thing happening on march6th?

### ISSUE THREAD

**Issue by cekuhnen** [GravitAG/gravit#260]
I do not see anything on the web and tried calling you guys today. I am very curious about what you might present - and so are my students who want to get away from Illustrator.

![screen shot 2015-02-13 at 9 44 50 pm](https://cloud.githubusercontent.com/assets/11001547/6527503/33d30998-c3e9-11e4-9552-d9410692f8dc.png)

**Comment by anderswelt** [comment]
We've sent out the beta invites and the final release date :)
