### ISSUE TITLE
Feature request: link images and not embed only

### ISSUE THREAD

**Issue by cekuhnen** [GravitAG/gravit#264]
looks like currently Gravit files include the images places and do not link to the file onto the HD:

![screen shot 2015-03-06 at 2 55 46 pm](https://cloud.githubusercontent.com/assets/11001547/6535186/f8567bc0-c410-11e4-955e-5f8fb39db8fc.png)
![screen shot 2015-03-06 at 2 56 34 pm](https://cloud.githubusercontent.com/assets/11001547/6535190/ff634bd2-c410-11e4-9f87-fe61cc86804d.png)

**Comment by anderswelt** [comment]
already fixed in current code :)
